// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: process.env.NODE_ENV === "production"
      ? "node dist/src/auth/seed.prisma.js"
      : "npx tsx src/auth/seed.prisma.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
